package lox.parser

import lox.Environment

// Generated by generate_ast ast 2024-01-20 22:27:33

interface Expr { 
    fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R
}

interface ExprVisitor<R> {
    fun visitBinary(expr: Binary, environment: Environment): R
	fun visitCall(expr: Call, environment: Environment): R
	fun visitGrouping(expr: Grouping, environment: Environment): R
	fun visitBlock(expr: Block, environment: Environment): R
	fun visitWhen(expr: When, environment: Environment): R
	fun visitLiteral(expr: Literal, environment: Environment): R
	fun visitUnary(expr: Unary, environment: Environment): R
	fun visitVariableExpression(expr: VariableExpression, environment: Environment): R
	fun visitSubscription(expr: Subscription, environment: Environment): R
	fun visitSlice(expr: Slice, environment: Environment): R
}

class Binary(val left: Expr, val operator: Token, val right: Expr) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitBinary(this, environment)
    }
}

class Call(val callee: Expr, val paren: Token, val arguments: List<Expr>) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitCall(this, environment)
    }
}

class Grouping(val expression: Expr) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitGrouping(this, environment)
    }
}

class Block(val statements: List<Stmt>) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitBlock(this, environment)
    }
}

class When(val initializer: Expr?, val cases: List<CasePair>, val catchall: Expr?) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitWhen(this, environment)
    }
}

class Literal(val value: Any?) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitLiteral(this, environment)
    }
}

class Unary(val operator: Token, val right: Expr) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitUnary(this, environment)
    }
}

class VariableExpression(val name: Token) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitVariableExpression(this, environment)
    }
}

class Subscription(val left: Expr, val index: Expr) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitSubscription(this, environment)
    }
}

class Slice(val left: Expr, val start: Expr, val end: Expr) : Expr {
    override fun<R> accept(visitor: ExprVisitor<R>, environment: Environment): R {
        return visitor.visitSlice(this, environment)
    }
}
